### ISSUE TITLE
Backtick syntax

### ISSUE THREAD

**Issue by crazy4groovy** [shuhei/todomvc-choo#1]
Hello, it's a very good demo app!

Can you explain this syntax?

```
... choo.view`
<html>...
</html>
`
```

How does the backtick work in this case?

**Comment by shuhei** [comment]
It's a tagged template literal. Please see the following page for the detail. The `choo.view` function receives the static pieces of the tremplate literal and values in `${}`s.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

**Comment by crazy4groovy** [comment]
Very cool, thank you! :+1:

**Comment by shuhei** [comment]
No problem 👍
