### ISSUE TITLE
Effects are called after reducers?

### ISSUE THREAD

**Issue by nickoneill** [shuhei/todomvc-choo#2]
Hi - curious about how your effects are triggered here. It looks like they're named the same things as the reducers but I don't see what ends up calling them directly.

**Comment by shuhei** [comment]
Yes, [effects are called after reducers](https://github.com/yoshuawuyts/barracks/blob/v9.0.0/index.js#L223-L245). They are both called when an action is sent with `send()`. Their `object` keys are names of actions, which is the first argument of `send()` without namespace.

According to [the choo's README](https://github.com/yoshuawuyts/choo#concepts):

>- **effects**: asynchronous functions that emit an action when done
>- **reducers**: synchronous functions that modify state

A reducer is a function that synchronously returns a new state. An effect is a function that doesn't return anything but does some side effects, such as AJAX, something that may fail, sending actions, etc.

**Comment by shuhei** [comment]
There are some similar patterns in the JavaScript frontend ecosystem.

In [Elm](https://github.com/elm-lang), which [inspired the author of choo](https://github.com/yoshuawuyts/choo#hey-doesnt-this-look-a-lot-like-elm), a reducer (called `update()`) returns a pair of new state and one or zero`Command`, which was called as "Effect" until Elm 0.16. The command is executed and eventually sends a `Msg`, which is something like an action in choo.

In the [redux](https://github.com/reactjs/redux) eco-system, [redux-saga](https://github.com/yelouafi/redux-saga) and [redux-observable](https://github.com/redux-observable/redux-observable) provide mechanisms to write functions that receive actions, do some side effects, and send (`dispatch()` in redux) actions.

**Comment by nickoneill** [comment]
Thanks! This is how I thought it worked, now just have to find out why the code I inherited does *not* do that :)

**Comment by nickoneill** [comment]
Sorry - one more thing. It looks like the convenience of having two of the same-named reducers/effects has changed in choo 3: https://github.com/yoshuawuyts/choo/issues/202

For example, save is clearly being called on your example todo site but a fresh npm install on a clone of this repo isn't ever saving to localstorage. How would I accomplish this today?

**Comment by shuhei** [comment]
Sorry, I might have misread the code. You are right, [an effect is not called when a reducer is called](https://github.com/yoshuawuyts/barracks/blob/v8.3.2/index.js#L240).

**Comment by shuhei** [comment]
I made this repo with choo 1.3.0 and updated it to 3.3.0 but didn't update the demo on github page.

Sorry for the confusion. I'll fix the code and demo.

**Comment by shuhei** [comment]
We can have two actions, one is for an effect that triggers the other action for a reducer. But there might be easier ways to do it.

I didn't know about the change of choo@3. Thanks for letting me know. I'll check other repos that use choo@3.

**Comment by shuhei** [comment]
A possible way to save state in local storage after a reducer might be using [the `onStateChange` hook](https://github.com/yoshuawuyts/choo#appusehooks).

**Comment by yoshuawuyts** [comment]
ohh didn't know that Elm had updated their language, thanks for pointing me
to that! :D

**Comment by shuhei** [comment]
@yoshuawuyts Ah, I didn't that you didn't know that. :-)
