### ISSUE TITLE
Unable to install dependencies using yarn

### ISSUE THREAD

**Issue by tbranyen** [shuhei/todomvc-choo#4]
Feel free to close if you don't think this is an addressable issue, but when trying to install dependencies using yarn, I see the following output:

```
λ yarn
yarn install v0.20.3
info No lockfile found.
[1/4] Resolving packages...
warning hyperstream > trumpet > html-tokenize > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
error webdriver-manager@11.1.1: The engine "node" is incompatible with this module. Expected version ">=6.9.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

However the install succeeds just fine with npm, which is probably good enough.

**Comment by shuhei** [comment]
It seems like webdriver-manager requires Node >= 6.9. Which version of Node are you using? Yarn seems to be strict about engine field of package.json.

**Comment by tbranyen** [comment]
Makes sense, doesn't seem to be actionable on this end. I'll close out!
